name: sportifyy
description: "A new Flutter project."
publish_to: 'none' # Use this for private packages. Remove to publish to pub.dev.

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  lottie: ^3.1.0
  provider: ^6.0.2
  get_it: ^7.2.0
  get_it_mixin: ^4.2.2
  injectable: ^1.5.3
  dartz: ^0.10.1
  supabase_flutter: ^2.5.2
  fluttertoast: ^8.0.8
  font_awesome_flutter: ^10.7.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 
  build_runner: ^2.1.4
  injectable_generator: ^1.5.3


flutter:
  uses-material-design: true

  assets:
    - assets/images/sign_up_page_image.png
    - assets/images/story_image_01.png
    - assets/images/story_image_02.png
    - assets/images/story_image_03.png
    - assets/gifs/
    - assets/json/player_animation.json
    - assets/json/ball_animation.json
    - assets/sounds/


  # If you have fonts, uncomment and fill out the following section
  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Regular.ttf
        - asset: fonts/Rubik-Bold.ttf
          weight: 700
        - asset: fonts/Rubik-Black.ttf
          weight: 900
